config/routes.rb
OberlinexcoOrg::Application.routes.draw do

  resources :excos do
    collection do
      get 'all'
      get 'admin'
    end
  end

  devise_for :users
  resources :users

  root :to => 'home#index'
  match 'apply_to_teach' => 'home#apply_to_teach', as: :apply_to_teach

end

app/models/exco.rb
class Exco < ActiveRecord::Base

  attr_accessible :name, :credits, :course_number,
                  # instructed_by is a string of instructor names who are not users
                  :instructed_by,
                  :description, :enrollment_limit, :year, :term

  has_and_belongs_to_many :instructors, class_name: 'User', join_table: 'excos_instructors'
  attr_accessible :instructors, :instructors_attributes

  TERMS = ['Fall', 'Spring']

  validates_presence_of :name, :credits, :course_number, :enrollment_limit, :year, :term
  validate :credits_is_positive
  validate :term_is_valid
  validate :name_is_unique_on_year_and_term
  validate :course_number_is_unique_on_year_and_term
  validate :enrollment_limit_is_positive
  validates_associated :instructors, message: "are invalid"

  scope :by_offered, order("year DESC, term ASC")
  scope :by_course_number, order(:course_number)

  def credits_is_positive
    if self.credits
      errors.add(:credits, 'must be positive') unless self.credits > 0
    end
  end

  def term_is_valid
    errors.add(:term, 'is not valid') unless TERMS.include? self.term
  end

  def name_is_unique_on_year_and_term
    # we have to check id to make sure we're not selecting self
    others = Exco.where{|o| (o.year == self.year) & (o.term == self.term) & (o.name == self.name) & (o.id != self.id)}
    unless others.empty?
      errors.add(:name, "conflicts with #{others.first.name} (#{others.first.course_number}), #{self.term} #{self.year}") 
    end
  end

  def course_number_is_unique_on_year_and_term
    # we have to check id to make sure we're not selecting self
    others = Exco.where{|o| (o.year == self.year) & (o.term == self.term) & (o.course_number == self.course_number) & (o.id != self.id)}
    unless others.empty?
      errors.add(:course_number, "conflicts with #{others.first.name} (#{others.first.course_number}), #{self.term} #{self.year}") 
    end
  end

  def enrollment_limit_is_positive
    if self.enrollment_limit
      errors.add(:enrollment_limit, 'must be positive') unless self.enrollment_limit > 0
    end
  end

  # Returns the current excos.
  #
  # The cutoff month for Fall to Spring semesters is 1 January, and for Spring to Fall is 1 June
  def self.current
    Exco.where(:year => Date.today.year, :term => (Date.today.month > 5 ? 'Fall' : 'Spring')).order(:course_number)
  end

  # Returns the formatted string for when this exco was offered.
  def offered
    self.term.titleize + " " + self.year.to_s
  end

  # Ties this record to specified users as instructors.
  # Takes a hash of the form:
  #
  #   {"0"=>{"t_number"=>"T00000001", "_destroy"=>"false"},
  #    "1"=>{"t_number"=>"T12345678", "_destroy"=>"false"},
  #    "2"=>{"t_number"=>"", "_destroy"=>"1"}}
  #
  # If there is no user with the given t_number, we initialize dummy objects that
  # hold the value but are not saved in the database and thus are invalid
  #
  # This was built for creating Excos with instructors (see /app/views/excos/_form).
  def instructors_attributes=(attributes)
    self.instructors = []
    attributes.each do |i, instructor|
      self.instructors << User.find_or_initialize_by_t_number(instructor["t_number"]) unless instructor["_destroy"] == "1"
    end
  end

end

app/controllers/excos_controller.rb
class ExcosController < ApplicationController

  # we check all authorizations in the standard fashion except :all due to namespace collision
  # we authorize :all in the method itself (see below)
  load_and_authorize_resource

  # GET /excos
  # GET /excos.json
  def index
    @excos = Exco.current.by_course_number

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @excos }
    end
  end

  # GET /excos/all
  # GET /excos/all.json
  def all
    @excos = Exco.by_offered.by_course_number

    respond_to do |format|
      format.html { render :index } # index.html.haml
      format.json { render json: @excos }
    end
  end

  # GET /excos/1
  # GET /excos/1.json
  def show
    @exco = Exco.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @exco }
    end
  end

  # GET /excos/new
  # GET /excos/new.json
  def new
    @exco = Exco.new
    @exco.instructors.build

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @exco }
    end
  end

  # GET /excos/1/edit
  def edit
    @exco = Exco.find(params[:id])
  end

  # POST /excos
  # POST /excos.json
  def create
    @exco = Exco.new(params[:exco])

    respond_to do |format|
      if @exco.save
        format.html { redirect_to @exco, notice: 'Exco was successfully created.' }
        format.json { render json: @exco, status: :created, location: @exco }
      else
        format.html { render action: "new" }
        format.json { render json: @exco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /excos/1
  # PUT /excos/1.json
  def update
    @exco = Exco.find(params[:id])

    respond_to do |format|
      if @exco.update_attributes(params[:exco])
        format.html { redirect_to @exco, notice: 'Exco was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excos/1
  # DELETE /excos/1.json
  def destroy
    @exco = Exco.find(params[:id])
    @exco.destroy

    respond_to do |format|
      format.html { redirect_to excos_path }
      format.json { head :no_content }
    end
  end

end

app/helpers/excos_helper.rb
module ExcosHelper
end

app/views/excos/_form.html.haml
= form_for(@exco) do |f|
  - if @exco.errors.any?
    #error_explanation
      %h2
        = pluralize(@exco.errors.count, "error")
        prohibited this exco from being saved:
      %ul
        - @exco.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :course_number
    %br/
    = f.number_field :course_number
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :credits
    %br/
    = f.number_field :credits
  .field
    = f.label :instructed_by
    %br/
    = f.text_field :instructed_by
  -# we're not using users linked to excos as instructors (yet!) ~ihm 1 September 2012
    .field
      = f.fields_for :instructors do |builder|
        = render "instructor_fields", :f => builder
      = link_to_add_fields "Add Instructor", f, :instructors
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :enrollment_limit
    %br/
    = f.number_field :enrollment_limit
  .field
    = f.label :year
    %br/
    = f.number_field :year
  .field
    = f.label :term
    %br/
    = f.select :term, Exco::TERMS.collect{|t| [t,t]}
  .actions
    = f.submit

app/views/excos/_instructor_fields.html.haml
.fields
  = f.label :t_number, "Instructor T number"
  %br/
  = f.text_field :t_number
  = link_to_remove_fields "remove", f

app/views/excos/_mini_table.html.haml
- excos_by_offered = @excos.group_by {|e| e.offered}
- excos_by_offered.each do |offered, excos|
  %h3= offered
  %table.table.table-striped
    %tr
      %th Name
      %th Instructor
    - excos.each do |exco|
      %tr
        %td= link_to exco.name, exco
        %td= (exco.instructors.map{|i| i.name} + (exco.instructed_by.blank? ? [] :  [exco.instructed_by])).join(", ")

app/views/excos/edit.html.haml
.page-header
  %h1 Edit ExCo

= render 'form'

app/views/excos/index.html.haml
.page-header
  %h1 ExCos

- if can? :create, Exco
  %p
    = link_to 'New Exco', new_exco_path, class: 'btn'

- excos_by_offered = @excos.group_by {|e| e.offered}
- excos_by_offered.each do |offered, excos|
  %h3= offered
  %table.table.table-striped
    %tr
      %th Course number
      %th Name
      %th Credits
      %th Instructor
      %th Enrollment limit
      - if can? :update, Exco
        %th
      - if can? :delete, Exco
        %th
    - excos.each do |exco|
      %tr
        %td= exco.course_number
        %td= link_to exco.name, exco
        %td= exco.credits
        %td= (exco.instructors.map{|i| i.name} + (exco.instructed_by.blank? ? [] :  [exco.instructed_by])).join(", ")
        %td= exco.enrollment_limit
        - if can? :update, Exco
          %td= link_to 'Edit', edit_exco_path(exco)
        - if can? :delete, Exco
          %td= link_to 'Destroy', exco, confirm: 'Are you sure?', method: :delete

app/views/excos/new.html.haml
.page-header
  %h1 New ExCo

= render 'form'

app/views/excos/show.html.haml
.page-header
  %h1
    = "#{@exco.course_number} - #{@exco.name}"

%p
  Instructed by
  %b= "#{(@exco.instructors.map{|i| i.name} + (@exco.instructed_by.blank? ? [] :  [@exco.instructed_by])).join(", ")},"
  = "0-#{@exco.credits}"
  credits

%p
  %span.label
    = @exco.term
    = @exco.year

%p
  = @exco.description

%p
  Enrollment Limit:
  %b= @exco.enrollment_limit