config/routes.rb
OberlinexcoOrg::Application.routes.draw do

  resources :excos do
    collection do
      get 'all'
      get 'admin'
    end
  end

  devise_for :users
  resources :users

  root :to => 'home#index'
  match 'apply_to_teach' => 'home#apply_to_teach', as: :apply_to_teach

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - unless name == :timedout
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %title= content_for?(:title) ? yield(:title) : "Oberlin ExCo"
        = csrf_meta_tags
        / Le HTML5 shim, for IE6-8 support of HTML elements
        /[if lt IE 9]
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
        = stylesheet_link_tag "application", :media => "all"
        /%link{:href => "/images/favicon.ico", :rel => "shortcut icon"}
        /%link{:href => "/images/apple-touch-icon.png", :rel => "apple-touch-icon"}
        /%link{:href => "/images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes=> "72x72"}
        /%link{:href => "/images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes=> "114x114"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            = link_to "Oberlin ExCo", root_path, :class => 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to "Current ExCos", excos_path
              %li= link_to "All ExCos", all_excos_path
              %li= link_to "Apply to Teach", apply_to_teach_path
              -if can? :find, User
                %li= link_to "Users", users_path
            -if user_signed_in?
              %ul.nav.sign_out
                %li= link_to "Log out", destroy_user_session_path, :method => :delete
    / /.navbar-fixed-top
    .content
      .container
        .messages
          = render "layouts/messages"
          / TODO this should be removed post-2012-11-02
          .row
            .alert.alert-error
              - if Date.parse("2014-10-31") > Date.today
                = link_to "Applications to teach", apply_to_teach_path
                a Spring 2015 ExCo are due October 31st.
              - else
                Applications to teach a Spring 2015 ExCo are closed.
        = yield
      / /container
    / /content
    %footer
      .container.muted
        %ul
          %h5 © 2012 Oberlin Experimental College
          %li= link_to "exco@oberlin.edu", 'mailto:exco@oberlin.edu'
          %li= link_to "Wilder 302", 'http://new.oberlin.edu/office/student-union/'
          %h5 Admin
          -if can? :find, User
            %li= link_to "Users", users_path
          -if user_signed_in?
            %li= link_to "Log out", destroy_user_session_path, :method => :delete
            %li= link_to "Account settings", edit_user_registration_path
          -else
            %li= link_to "Log in", new_user_session_path
        %ul
          %h5 Contributors
          %li= link_to "Isaac Hollander McCreery", 'http://cs.oberlin.edu/~ihm'
          %li= link_to "Malcolm Balch-Crystal IV", 'http://malcolmbalchcrystal.com'
          %h5 Source
          %li= link_to "GitHub", 'http://www.github.com/ihmccreery/oberlinexco.org'
      / /container
    / /footer
    / Javascripts
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"